HELM_FLAGS=
{{ if has "jenkins" .Apps -}}
HELM_FLAGS+=-f jenkins.values.yaml
{{- end }}
{{ if has "prometheus" .Apps -}}
HELM_FLAGS+=-f prometheus.values.yaml
{{- end }}
{{ if has "meta-monitoring" .Apps -}}
HELM_FLAGS+=-f meta-monitoring.values.yaml
{{- end }}

setup:
	helm dependency update
	minikube kubectl -- create namespace devops || true
	minikube kubectl -- create secret generic minio -n devops --from-literal=rootPassword=admin123 --from-literal=rootUser=admin

install:
	helm install -n devops devops . $(HELM_FLAGS)

upgrade:
	helm upgrade -n devops devops . $(HELM_FLAGS)

uninstall:
	helm uninstall -n devops devops

{{ if has "jenkins" .Apps -}}
jenkins-credentials:
	@minikube kubectl -- -n devops get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.user}' | base64 -d
	@echo ""
	@minikube kubectl -- -n devops get secret jenkins-operator-credentials-jenkins -o 'jsonpath={.data.password}' | base64 -d
	@echo ""

jenkins-connect:
	@minikube kubectl -- -n devops port-forward jenkins-jenkins 8080:8080
{{- end }}

