apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-operator-http-jenkins
  labels:
    app: jenkins-operator
    jenkins-cr: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins-operator
  endpoints:
    - port: web
